### ISSUE TITLE
Utils and Timeseries Missing

### ISSUE THREAD

**Issue by davidkurtenb** [SyedHasnat/Papers#2]
There is not utils in the codebase but the scripts try to import it.

**Comment by SyedHasnat** [comment]
Thanks for reaching out!
Utils.py contains the custom callbacks and time series data generator. 
For callbacks you can use keras built-in callbacks and for time time series data generator you can go through the two algorithms mentioned in the paper. Further more, if you have any confusion in implication of the given algos you can go through my another repo 
https://github.com/SyedHasnat/CNNs-LSTMs-Time-Series
Thank you 🙂
